# Generated by Django 5.2 on 2025-04-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='Name', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='Surname', max_length=255),
        ),
    ]
