# Generated by Django 5.2 on 2025-05-06 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_category_slug_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_file',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apps.product'),
        ),
    ]
