# Generated by Django 5.2 on 2025-05-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_user_district_user_first_name_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
