# Generated by Django 5.2 on 2025-05-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
