# Generated by Django 5.2 on 2025-05-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_order_quantity_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
