# Generated by Django 5.2 on 2025-05-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_settings_delivery_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='order_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_address',
        ),
        migrations.DeleteModel(
            name='OrderAddress',
        ),
    ]
