# Generated by Django 5.2 on 2025-05-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_remove_query_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='stream_ordering',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
