# Generated by Django 5.2 on 2025-05-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_remove_order_payment_alter_order_stream_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='link',
        ),
    ]
