# Generated by Django 5.2 on 2025-05-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_remove_stream_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
