# Generated by Django 5.2 on 2025-05-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_product_seller_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
