# Generated by Django 5.2 on 2025-05-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_stream_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('hold', 'Hold'), ('archived', 'Archived')], default='pending', max_length=255),
        ),
    ]
