# Generated by Django 5.2 on 2025-05-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('hold', 'Hold'), ('archived', 'Archived')], default='new', max_length=255),
        ),
    ]
