# Generated by Django 5.2 on 2025-05-19 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stream_ordering',
        ),
        migrations.AddField(
            model_name='order',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='apps.stream'),
        ),
    ]
