# Generated by Django 5.2 on 2025-05-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_remove_order_stream_ordering_order_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='order_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
