# Generated by Django 5.2 on 2025-05-21 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_region_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('under view', 'Under View'), ('completed', 'Completed')], default='under view'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payments'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
