# Generated by Django 5.2 on 2025-05-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_payment_created_at_payment_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
